# Generated by Django 3.1.1 on 2020-11-16 17:34
# pylint: disable=invalid-name

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="completesurvey",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.answer",
            ),
        ),
        migrations.AddField(
            model_name="completesurvey",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.question",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.answer",
            ),
        ),
    ]
