# Generated by Django 3.1.1 on 2020-11-16 17:48
# pylint: disable=invalid-name

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_questionanswer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="questions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.question",
            ),
        ),
        migrations.DeleteModel(
            name="QuestionAnswer",
        ),
    ]
