# Generated by Django 3.1.1 on 2020-11-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_auto_20201116_1748"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="questions",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="answer",
        ),
    ]
