# Generated by Django 3.1.1 on 2020-12-29 16:39
# pylint: disable=invalid-name

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_auto_20201214_1447"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,  # noqa: E501 fmt: off
                        to="surveys.user",  # fmt: on
                    ),
                ),
            ],
        ),
    ]
