# Generated by Django 3.1.1 on 2020-12-29 16:55
# pylint: disable=invalid-name

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.TextField(null=True),
        ),
    ]
