# Generated by Django 3.1.1 on 2021-01-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_auto_20201229_1655"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="user_id",
            new_name="user",
        ),
    ]
