# Generated by Django 3.1.1 on 2021-01-31 21:09
# pylint: disable=invalid-name

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0013_question_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
