# Generated by Django 3.1.1 on 2021-03-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20210201_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
