# Generated by Django 3.1.1 on 2021-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0018_auto_20210312_0719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completesurvey",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
